-- Countries the research agent may plan scrapes for.
--
-- Source: clockworks/tiktok-scraper, input field `proxyCountryCode` — the
-- actor's own list of geo-targetable countries, captured 2026-09-08.
--
-- SCOPE: this table is for the AI research agent ONLY. It deliberately does
-- not touch `markets`, which stays the source of truth for the scrape
-- pipelines, dashboards and everything keyed on market_id.
--
-- Refresh it later with:  python scripts/sync_apify_countries.py
--
-- NULLABLE BY DESIGN:
--   region    the model resolves "the Gulf" or "MENA" from its own geography.
--             Fill this in only to override that with your own grouping.
--   aliases   the model already maps "Dubai", "KSA", "Türkiye" and "Brasil"
--             correctly on its own. Seeded here only where a nickname is
--             common enough to be worth pinning; add your own business
--             shorthand and it takes effect on the next context build.
--             NOTE: codes here are ISO-2. "dubai" maps to AE, not UAE —
--             UAE is the `markets` code and does not exist in this table.

create table if not exists apify_supported_countries (
  id            uuid primary key default gen_random_uuid(),
  country_code  text not null unique,          -- ISO-2, as the actor expects
  name          text not null,
  region        text,                          -- optional override; LLM infers when null
  aliases       text[] not null default '{}',  -- optional nicknames
  languages     text[] not null default '{}',  -- for hashtag localisation
  is_active     boolean not null default true, -- disable without deleting
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists apify_supported_countries_active_idx
  on apify_supported_countries (is_active, country_code);

alter table apify_supported_countries enable row level security;

insert into apify_supported_countries (country_code, name, aliases) values
  ('AD', 'Andorra', '{}'),
  ('AE', 'United Arab Emirates', array['uae', 'emirates', 'dubai', 'abu dhabi']),
  ('AF', 'Afghanistan', '{}'),
  ('AG', 'Antigua and Barbuda', '{}'),
  ('AI', 'Anguilla', '{}'),
  ('AL', 'Albania', '{}'),
  ('AM', 'Armenia', '{}'),
  ('AO', 'Angola', '{}'),
  ('AR', 'Argentina', '{}'),
  ('AS', 'American Samoa', '{}'),
  ('AT', 'Austria', '{}'),
  ('AU', 'Australia', '{}'),
  ('AX', 'Åland', '{}'),
  ('AZ', 'Azerbaijan', '{}'),
  ('BA', 'Bosnia and Herzegovina', '{}'),
  ('BB', 'Barbados', '{}'),
  ('BE', 'Belgium', '{}'),
  ('BF', 'Burkina Faso', '{}'),
  ('BG', 'Bulgaria', '{}'),
  ('BH', 'Bahrain', '{}'),
  ('BI', 'Burundi', '{}'),
  ('BJ', 'Benin', '{}'),
  ('BM', 'Bermuda', '{}'),
  ('BN', 'Brunei', '{}'),
  ('BO', 'Bolivia', '{}'),
  ('BR', 'Brazil', array['brasil']),
  ('BS', 'Bahamas', '{}'),
  ('BT', 'Bhutan', '{}'),
  ('BW', 'Botswana', '{}'),
  ('BY', 'Belarus', '{}'),
  ('BZ', 'Belize', '{}'),
  ('CA', 'Canada', '{}'),
  ('CD', 'Democratic Republic of the Congo', '{}'),
  ('CG', 'Republic of the Congo', '{}'),
  ('CH', 'Switzerland', '{}'),
  ('CI', 'Ivory Coast', '{}'),
  ('CK', 'Cook Islands', '{}'),
  ('CL', 'Chile', '{}'),
  ('CM', 'Cameroon', '{}'),
  ('CO', 'Colombia', '{}'),
  ('CR', 'Costa Rica', '{}'),
  ('CV', 'Cape Verde', '{}'),
  ('CY', 'Cyprus', '{}'),
  ('CZ', 'Czech Republic', array['czechia']),
  ('DE', 'Germany', '{}'),
  ('DJ', 'Djibouti', '{}'),
  ('DK', 'Denmark', '{}'),
  ('DO', 'Dominican Republic', '{}'),
  ('DZ', 'Algeria', '{}'),
  ('EC', 'Ecuador', '{}'),
  ('EE', 'Estonia', '{}'),
  ('EG', 'Egypt', '{}'),
  ('ES', 'Spain', '{}'),
  ('ET', 'Ethiopia', '{}'),
  ('FI', 'Finland', '{}'),
  ('FJ', 'Fiji', '{}'),
  ('FK', 'Falkland Islands', '{}'),
  ('FR', 'France', '{}'),
  ('GA', 'Gabon', '{}'),
  ('GB', 'United Kingdom', array['uk', 'britain', 'england']),
  ('GD', 'Grenada', '{}'),
  ('GE', 'Georgia', '{}'),
  ('GH', 'Ghana', '{}'),
  ('GI', 'Gibraltar', '{}'),
  ('GL', 'Greenland', '{}'),
  ('GN', 'Guinea', '{}'),
  ('GP', 'Guadeloupe', '{}'),
  ('GR', 'Greece', '{}'),
  ('GT', 'Guatemala', '{}'),
  ('GW', 'Guinea-Bissau', '{}'),
  ('GY', 'Guyana', '{}'),
  ('HN', 'Honduras', '{}'),
  ('HR', 'Croatia', '{}'),
  ('HU', 'Hungary', '{}'),
  ('ID', 'Indonesia', '{}'),
  ('IE', 'Ireland', '{}'),
  ('IL', 'Israel', '{}'),
  ('IM', 'Isle of Man', '{}'),
  ('IQ', 'Iraq', '{}'),
  ('IS', 'Iceland', '{}'),
  ('IT', 'Italy', '{}'),
  ('JE', 'Jersey', '{}'),
  ('JM', 'Jamaica', '{}'),
  ('JP', 'Japan', '{}'),
  ('KE', 'Kenya', '{}'),
  ('KH', 'Cambodia', '{}'),
  ('KN', 'Saint Kitts and Nevis', '{}'),
  ('KR', 'South Korea', array['south korea', 'korea']),
  ('KW', 'Kuwait', '{}'),
  ('KY', 'Cayman Islands', '{}'),
  ('KZ', 'Kazakhstan', '{}'),
  ('LA', 'Laos', '{}'),
  ('LB', 'Lebanon', '{}'),
  ('LC', 'Saint Lucia', '{}'),
  ('LK', 'Sri Lanka', '{}'),
  ('LR', 'Liberia', '{}'),
  ('LS', 'Lesotho', '{}'),
  ('LT', 'Lithuania', '{}'),
  ('LU', 'Luxembourg', '{}'),
  ('LV', 'Latvia', '{}'),
  ('LY', 'Libya', '{}'),
  ('MA', 'Morocco', '{}'),
  ('MC', 'Monaco', '{}'),
  ('MD', 'Moldova', '{}'),
  ('ME', 'Montenegro', '{}'),
  ('MF', 'Saint Martin', '{}'),
  ('MG', 'Madagascar', '{}'),
  ('MH', 'Marshall Islands', '{}'),
  ('MK', 'North Macedonia', '{}'),
  ('ML', 'Mali', '{}'),
  ('MM', 'Myanmar [Burma]', '{}'),
  ('MN', 'Mongolia', '{}'),
  ('MO', 'Macao', '{}'),
  ('MQ', 'Martinique', '{}'),
  ('MR', 'Mauritania', '{}'),
  ('MT', 'Malta', '{}'),
  ('MU', 'Mauritius', '{}'),
  ('MV', 'Maldives', '{}'),
  ('MW', 'Malawi', '{}'),
  ('MX', 'Mexico', array['méxico']),
  ('MY', 'Malaysia', '{}'),
  ('MZ', 'Mozambique', '{}'),
  ('NA', 'Namibia', '{}'),
  ('NG', 'Nigeria', '{}'),
  ('NI', 'Nicaragua', '{}'),
  ('NL', 'Netherlands', array['holland']),
  ('NO', 'Norway', '{}'),
  ('NP', 'Nepal', '{}'),
  ('NR', 'Nauru', '{}'),
  ('NZ', 'New Zealand', '{}'),
  ('OM', 'Oman', '{}'),
  ('PA', 'Panama', '{}'),
  ('PE', 'Peru', '{}'),
  ('PF', 'French Polynesia', '{}'),
  ('PG', 'Papua New Guinea', '{}'),
  ('PH', 'Philippines', '{}'),
  ('PL', 'Poland', '{}'),
  ('PM', 'Saint Pierre and Miquelon', '{}'),
  ('PR', 'Puerto Rico', '{}'),
  ('PS', 'Palestine', '{}'),
  ('PT', 'Portugal', '{}'),
  ('PY', 'Paraguay', '{}'),
  ('QA', 'Qatar', '{}'),
  ('RE', 'Réunion', '{}'),
  ('RO', 'Romania', '{}'),
  ('RS', 'Serbia', '{}'),
  ('RU', 'Russia', '{}'),
  ('RW', 'Rwanda', '{}'),
  ('SA', 'Saudi Arabia', array['ksa', 'saudi']),
  ('SB', 'Solomon Islands', '{}'),
  ('SE', 'Sweden', '{}'),
  ('SG', 'Singapore', '{}'),
  ('SK', 'Slovakia', '{}'),
  ('SL', 'Sierra Leone', '{}'),
  ('SM', 'San Marino', '{}'),
  ('SN', 'Senegal', '{}'),
  ('SO', 'Somalia', '{}'),
  ('SR', 'Suriname', '{}'),
  ('SV', 'El Salvador', '{}'),
  ('SX', 'Sint Maarten', '{}'),
  ('SZ', 'Swaziland', '{}'),
  ('TC', 'Turks and Caicos Islands', '{}'),
  ('TD', 'Chad', '{}'),
  ('TG', 'Togo', '{}'),
  ('TH', 'Thailand', '{}'),
  ('TJ', 'Tajikistan', '{}'),
  ('TN', 'Tunisia', '{}'),
  ('TO', 'Tonga', '{}'),
  ('TR', 'Turkey', array['turkiye', 'türkiye']),
  ('TT', 'Trinidad and Tobago', '{}'),
  ('TV', 'Tuvalu', '{}'),
  ('TW', 'Taiwan', '{}'),
  ('TZ', 'Tanzania', '{}'),
  ('UA', 'Ukraine', '{}'),
  ('UG', 'Uganda', '{}'),
  ('US', 'United States', array['usa', 'america', 'the states']),
  ('UY', 'Uruguay', '{}'),
  ('VC', 'Saint Vincent and the Grenadines', '{}'),
  ('VE', 'Venezuela', '{}'),
  ('VG', 'British Virgin Islands', '{}'),
  ('VI', 'U.S. Virgin Islands', '{}'),
  ('VN', 'Vietnam', '{}'),
  ('WF', 'Wallis and Futuna', '{}'),
  ('XK', 'Kosovo', '{}'),
  ('YE', 'Yemen', '{}'),
  ('ZA', 'South Africa', '{}'),
  ('ZM', 'Zambia', '{}'),
  ('ZW', 'Zimbabwe', '{}')
on conflict (country_code) do nothing;
